cd cars/misc
mv ebaaerial.m aerial.m
mv ebaaerialt.m aerialt.m
cp ebas-ff8000.m aeriala.m
cp ebas-00ff00.m aerialb.m
cp ebas-ffff00.m aerialc.m
cp ebas-2020ff.m aeriald.m
cp ebas-910404.m aeriale.m
cp ebas-ffffff.m aerialf.m
cp ebas-ff00c4.m aerialg.m
cp aerial.m aerialh.m
cp aerial.m aeriali.m
cp aerial.m aerialj.m
cp aerial.m aerialk.m
cp aerial.m aeriall.m
cp aerial.m aerialm.m
cp ebas-ffffff.m aerialn.m
cp ebas-ffffff.m aerialo.m
cp ebas-ffffff.m aerialp.m
cp ebas-ffffff.m aerialq.m
cp ebas-ffffff.m aerialr.m
cp ebas-ffffff.m aerials.m
cp ebat-101010.m aerialta.m
cp ebat-101010.m aerialtb.m
cp ebat-101010.m aerialtc.m
cp ebat-101010.m aerialtd.m
cp ebat-101010.m aerialte.m
cp ebat-101010.m aerialtf.m
cp ebat-101010.m aerialtg.m
cp ebat-ff8000.m aerialth.m
cp ebat-00ff00.m aerialti.m
cp ebat-ffff00.m aerialtj.m
cp ebat-2020ff.m aerialtk.m
cp ebat-ffffff.m aerialtl.m
cp ebat-ff00c4.m aerialtm.m
cp ebat-ff8000.m aerialtn.m
cp ebat-00ff00.m aerialto.m
cp ebat-ffff00.m aerialtp.m
cp ebat-2020ff.m aerialtq.m
cp aerialt.m aerialtr.m
cp ebat-ff00c4.m aerialts.m
cd .. && cd .. && cd gfx
cp ebafxpage1.bmp fxpage1.bmp
